// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"webook/config"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
	"webook/ioc"
)

// Injectors from wire.go:

// InitWebServer 初始化 Web 服务器，使用 Wire 进行依赖注入
func InitWebServer() *gin.Engine {
	configConfig := config.Load()
	db := ioc.NewDB(configConfig)
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.NewRedis(configConfig)
	userCacheExpiration := ProvideUserCacheExpiration(configConfig)
	userCache := cache.NewUserCache(cmdable, userCacheExpiration)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	jwtExpireTime := ProvideJWTExpireTime(configConfig)
	userHandler := web.NewUserHandler(userService, jwtExpireTime)
	engine := ioc.NewGinEngine(configConfig, userHandler)
	return engine
}

// wire.go:

// ProvideUserCacheExpiration 提供用户缓存过期时间
func ProvideUserCacheExpiration(cfg *config.Config) cache.UserCacheExpiration {
	return cache.UserCacheExpiration(cfg.Cache.UserExpiration)
}

// ProvideJWTExpireTime 提供 JWT 过期时间
func ProvideJWTExpireTime(cfg *config.Config) web.JWTExpireTime {
	return web.JWTExpireTime(cfg.JWT.ExpireTime)
}
