// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"time"

	"webook/config"
	web "webook/internal/adapters/inbound/http"
	dao "webook/internal/adapters/outbound/persistence/mysql"
	cache "webook/internal/adapters/outbound/persistence/redis"
	"webook/internal/adapters/outbound/repository"
	"webook/internal/application"
	"webook/internal/ioc"

	"github.com/gin-gonic/gin"
)

// InitWebServer initializes the web server.
func InitWebServer(cfg *config.Config) *gin.Engine {
	db := ioc.NewDB(cfg)
	userDAO := dao.NewUserDAO(db)
	postDAO := dao.NewPostDAO(db)
	publishedPostDAO := dao.NewPublishedPostDAO(db)
	postStatsDAO := dao.NewPostStatsDAO(db)
	postLikeDAO := dao.NewPostLikeDAO(db)
	postCollectDAO := dao.NewPostCollectDAO(db)
	cmdable := ioc.NewRedis(cfg)
	userCacheExpiration := ProvideUserCacheExpiration(cfg)
	userCache := cache.NewUserCache(cmdable, userCacheExpiration)
	tokenBlacklist := cache.NewTokenBlacklist(cmdable)
	postCache := cache.NewPostCache(cmdable)
	postStatsCache := cache.NewPostStatsCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO)
	cachedUserRepository := repository.NewCachedUserRepository(userRepository, userCache)
	postRepository := repository.NewPostRepository(postDAO)
	publishedPostRepository := repository.NewPublishedPostRepository(publishedPostDAO)
	cachedPublishedPostRepository := repository.NewCachedPublishedPostRepository(publishedPostRepository, postCache)
	postStatsRepository := repository.NewPostStatsRepository(postStatsDAO)
	postLikeRepository := repository.NewPostLikeRepository(postLikeDAO)
	postCollectRepository := repository.NewPostCollectRepository(postCollectDAO)
	rabbitMQConn := ioc.NewRabbitMQConn(cfg)
	rabbitMQProducerChannel := ioc.NewRabbitMQProducerChannel(rabbitMQConn)
	postStatsPublisher := ioc.NewPostStatsPublisher(rabbitMQProducerChannel, cfg)
	userService := application.NewUserService(cachedUserRepository)
	postService := application.NewPostService(postRepository, cachedPublishedPostRepository)
	postInteractionService := application.NewPostInteractionService(postLikeRepository, postCollectRepository, postStatsRepository, postStatsCache, postStatsPublisher)
	jwtService := ioc.NewJWTService(cfg)
	tokenService := ioc.NewTokenService(jwtService)
	accessTokenVerifier := ioc.NewAccessTokenVerifier(jwtService)
	accessExpireTime := ProvideAccessExpireTime(cfg)
	refreshExpireTime := ProvideRefreshExpireTime(cfg)
	authService := application.NewAuthService(tokenService, tokenBlacklist, accessExpireTime, refreshExpireTime)
	userHandler := web.NewUserHandler(userService, authService)
	postHandler := web.NewPostHandler(postService, postInteractionService)
	logger := ioc.NewLogger(cfg)
	engine := ioc.NewGinEngine(cfg, userHandler, postHandler, accessTokenVerifier, logger)
	return engine
}

// InitPostStatsWorker initializes the stats worker.
func InitPostStatsWorker(cfg *config.Config) *application.PostStatsWorker {
	db := ioc.NewDB(cfg)
	postStatsDAO := dao.NewPostStatsDAO(db)
	cmdable := ioc.NewRedis(cfg)
	postStatsCache := cache.NewPostStatsCache(cmdable)
	postStatsRepository := repository.NewPostStatsRepository(postStatsDAO)
	logger := ioc.NewLogger(cfg)
	rabbitMQConn := ioc.NewRabbitMQConn(cfg)
	rabbitMQConsumerChannel := ioc.NewRabbitMQConsumerChannel(rabbitMQConn)
	postStatsConsumer := ioc.NewPostStatsConsumer(rabbitMQConsumerChannel, cfg, postStatsCache, logger)
	postStatsFlusher := application.NewPostStatsFlusher(postStatsCache, postStatsRepository, logger)
	postStatsWorker := application.NewPostStatsWorker(postStatsConsumer, postStatsFlusher)
	return postStatsWorker
}

// ProvideUserCacheExpiration provides user cache expiration.
func ProvideUserCacheExpiration(cfg *config.Config) cache.UserCacheExpiration {
	return cache.UserCacheExpiration(cfg.Cache.UserExpiration)
}

// ProvideAccessExpireTime provides access token expiration.
func ProvideAccessExpireTime(cfg *config.Config) time.Duration {
	return cfg.JWT.ExpireTime
}

// ProvideRefreshExpireTime provides refresh token expiration.
func ProvideRefreshExpireTime(cfg *config.Config) time.Duration {
	return cfg.JWT.RefreshExpireTime
}
