// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"time"

	"github.com/gin-gonic/gin"
	"webook/config"
	"webook/internal/ioc"
	"webook/internal/repository"
	"webook/internal/repository/cache"
	"webook/internal/repository/dao"
	"webook/internal/service"
	"webook/internal/web"
)

// InitWebServer initializes the web server.
func InitWebServer(cfg *config.Config) *gin.Engine {
	db := ioc.NewDB(cfg)
	userDAO := dao.NewUserDAO(db)
	postDAO := dao.NewPostDAO(db)
	publishedPostDAO := dao.NewPublishedPostDAO(db)
	cmdable := ioc.NewRedis(cfg)
	userCacheExpiration := ProvideUserCacheExpiration(cfg)
	userCache := cache.NewUserCache(cmdable, userCacheExpiration)
	tokenBlacklist := cache.NewTokenBlacklist(cmdable)
	postCache := cache.NewPostCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO)
	cachedUserRepository := repository.NewCachedUserRepository(userRepository, userCache)
	postRepository := repository.NewPostRepository(postDAO)
	publishedPostRepository := repository.NewPublishedPostRepository(publishedPostDAO)
	cachedPublishedPostRepository := repository.NewCachedPublishedPostRepository(publishedPostRepository, postCache)
	userService := service.NewUserService(cachedUserRepository)
	postService := service.NewPostService(postRepository, cachedPublishedPostRepository)
	jwtService := ioc.NewJWTService(cfg)
	tokenService := ioc.NewTokenService(jwtService)
	accessTokenVerifier := ioc.NewAccessTokenVerifier(jwtService)
	accessExpireTime := ProvideAccessExpireTime(cfg)
	refreshExpireTime := ProvideRefreshExpireTime(cfg)
	authService := service.NewAuthService(tokenService, tokenBlacklist, accessExpireTime, refreshExpireTime)
	userHandler := web.NewUserHandler(userService, authService)
	postHandler := web.NewPostHandler(postService)
	logger := ioc.NewLogger(cfg)
	engine := ioc.NewGinEngine(cfg, userHandler, postHandler, accessTokenVerifier, logger)
	return engine
}

// ProvideUserCacheExpiration provides user cache expiration.
func ProvideUserCacheExpiration(cfg *config.Config) cache.UserCacheExpiration {
	return cache.UserCacheExpiration(cfg.Cache.UserExpiration)
}

// ProvideAccessExpireTime provides access token expiration.
func ProvideAccessExpireTime(cfg *config.Config) time.Duration {
	return cfg.JWT.ExpireTime
}

// ProvideRefreshExpireTime provides refresh token expiration.
func ProvideRefreshExpireTime(cfg *config.Config) time.Duration {
	return cfg.JWT.RefreshExpireTime
}
